"""Small Caldera v2 API client for autonomous detection tests."""

from __future__ import annotations

import json
import ssl
import time
import uuid
from dataclasses import dataclass
from typing import Any, Mapping
from urllib.error import HTTPError, URLError
from urllib.parse import urljoin, urlparse
from urllib.request import Request, urlopen

from wazuh_sigma.active_testing.models import ActiveTestError, CalderaAbilitySpec
from wazuh_sigma.deploy.client import HttpResponse, Transport, redact_sensitive_text
from wazuh_sigma.wazuh_contract import validate_wazuh_host


class CalderaApiError(ActiveTestError):
    """Raised when Caldera rejects a request or returns unexpected data."""


@dataclass(frozen=True)
class CalderaAuth:
    """Header-based Caldera API authentication settings."""

    header_name: str = "KEY"
    token: str = ""
    scheme: str = ""

    def header_value(self) -> str:
        if not self.token:
            raise CalderaApiError("Caldera API token is required")
        if self.scheme:
            return f"{self.scheme} {self.token}"
        return self.token


class CalderaClient:
    """Minimal Caldera client using the documented ``/api/v2`` routes."""

    def __init__(
        self,
        base_url: str,
        auth: CalderaAuth,
        *,
        timeout: int = 30,
        verify_tls: bool = True,
        ca_bundle: str | None = None,
        transport: Transport | None = None,
    ) -> None:
        if timeout <= 0:
            raise CalderaApiError("Caldera timeout must be a positive integer")
        self.base_url = validate_wazuh_host(base_url, error_type=CalderaApiError).rstrip("/") + "/"
        self.auth = auth
        self.timeout = timeout
        self.verify_tls = verify_tls
        self.ca_bundle = ca_bundle
        self.transport = transport or self._urllib_transport

    def health(self) -> Mapping[str, Any]:
        """Return Caldera health information."""
        return self._request("GET", "api/v2/health")

    def list_agents(self) -> list[Mapping[str, Any]]:
        """Return Caldera agents."""
        payload = self._request("GET", "api/v2/agents")
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, Mapping)]
        raise CalderaApiError("Caldera agents response was not a list")

    def find_live_agent(self, *, platform: str, group: str | None = None) -> Mapping[str, Any]:
        """Find a live agent matching platform and optional group."""
        platform = platform.lower()
        for agent in self.list_agents():
            agent_platform = str(agent.get("platform", "")).lower()
            agent_group = str(agent.get("group", ""))
            status = str(agent.get("status", "")).lower()
            if agent_platform != platform:
                continue
            if group and agent_group != group:
                continue
            if status in {"dead", "untrusted", "gone"}:
                continue
            return agent
        group_hint = f" in group {group!r}" if group else ""
        raise CalderaApiError(f"no live Caldera {platform} agent found{group_hint}")

    def create_ability(self, *, name: str, spec: CalderaAbilitySpec, marker: str) -> Mapping[str, Any]:
        """Create a one-off ability that executes the configured safe command."""
        ability_id = str(uuid.uuid4())
        command = substitute_marker(spec.command, marker)
        cleanup = [substitute_marker(item, marker) for item in spec.cleanup]
        payload = {
            "ability_id": ability_id,
            "name": name,
            "description": "Generated by wazuh-sigma-pipeline active detection testing",
            "tactic": spec.tactic,
            "technique_id": spec.technique_id,
            "technique_name": spec.technique_name,
            "repeatable": True,
            "executors": [
                {
                    "name": spec.executor,
                    "platform": spec.platform,
                    "command": command,
                    "cleanup": cleanup,
                    "timeout": spec.timeout,
                }
            ],
        }
        return self._request("POST", "api/v2/abilities", body=payload)

    def create_adversary(self, *, name: str, ability_id: str) -> Mapping[str, Any]:
        """Create an adversary containing the generated ability."""
        payload = {
            "adversary_id": str(uuid.uuid4()),
            "name": name,
            "description": "Generated by wazuh-sigma-pipeline active detection testing",
            "atomic_ordering": [ability_id],
            "tags": ["wazuh-sigma-pipeline", "active-test"],
        }
        return self._request("POST", "api/v2/adversaries", body=payload)

    def create_operation(self, *, name: str, adversary: Mapping[str, Any], group: str) -> Mapping[str, Any]:
        """Create an autonomous Caldera operation for the selected agent group."""
        payload = {
            "name": name,
            "adversary": adversary,
            "group": group,
            "jitter": "0/0",
            "autonomous": 1,
            "auto_close": True,
            "visibility": 51,
        }
        return self._request("POST", "api/v2/operations", body=payload)

    def get_operation(self, operation_id: str) -> Mapping[str, Any]:
        """Fetch operation state."""
        return self._request("GET", f"api/v2/operations/{operation_id}")

    def list_links(self, operation_id: str) -> list[Mapping[str, Any]]:
        """Fetch operation links."""
        payload = self._request("GET", f"api/v2/operations/{operation_id}/links")
        if isinstance(payload, list):
            return [item for item in payload if isinstance(item, Mapping)]
        raise CalderaApiError("Caldera operation links response was not a list")

    def wait_for_operation(self, operation_id: str, *, timeout: int, poll_interval: int) -> Mapping[str, Any]:
        """Poll until operation closes or all links are terminal."""
        deadline = time.monotonic() + timeout
        last_operation: Mapping[str, Any] = {}
        while time.monotonic() < deadline:
            last_operation = self.get_operation(operation_id)
            state = str(last_operation.get("state", "")).lower()
            links = self.list_links(operation_id)
            if state in {"finished", "cleanup", "complete", "completed"} or _links_finished(links):
                return {"operation": last_operation, "links": links}
            time.sleep(poll_interval)
        raise CalderaApiError(f"Caldera operation {operation_id} did not finish within {timeout} seconds")

    def _headers(self, extra: Mapping[str, str] | None = None) -> dict[str, str]:
        headers = {
            self.auth.header_name: self.auth.header_value(),
            "Accept": "application/json",
        }
        if extra:
            headers.update(extra)
        return headers

    def _request(
        self,
        method: str,
        endpoint: str,
        *,
        body: Mapping[str, Any] | None = None,
    ) -> Any:
        raw_body = None
        headers = self._headers()
        if body is not None:
            raw_body = json.dumps(body).encode("utf-8")
            headers["Content-Type"] = "application/json"
        response = self.transport(method, urljoin(self.base_url, endpoint), raw_body, headers)
        if response.status < 200 or response.status >= 300:
            raise CalderaApiError(f"Caldera API {method} {endpoint} failed with HTTP {response.status}")
        if not response.body:
            return {}
        try:
            return json.loads(response.body.decode("utf-8"))
        except json.JSONDecodeError as error:
            raise CalderaApiError(f"Caldera API {method} {endpoint} returned non-JSON response") from error

    def _urllib_transport(
        self,
        method: str,
        url: str,
        body: bytes | None,
        headers: Mapping[str, str],
    ) -> HttpResponse:
        request = Request(url, data=body, headers=dict(headers), method=method)
        context = self._ssl_context(url)
        try:
            with urlopen(request, timeout=self.timeout, context=context) as response:
                return HttpResponse(
                    status=response.status,
                    body=response.read(),
                    headers=dict(response.headers.items()),
                )
        except HTTPError as error:
            body_bytes = error.read()
            body_preview = redact_sensitive_text(body_bytes.decode("utf-8", "replace"))
            raise CalderaApiError(
                f"Caldera API request failed with HTTP {error.code}: {body_preview}"
            ) from error
        except URLError as error:
            raise CalderaApiError(f"Caldera API connection failed: {error.reason}") from error

    def _ssl_context(self, url: str) -> ssl.SSLContext | None:
        if urlparse(url).scheme != "https":
            return None
        if not self.verify_tls:
            context = ssl.create_default_context()
            context.check_hostname = False
            context.verify_mode = ssl.CERT_NONE
            return context
        if self.ca_bundle:
            return ssl.create_default_context(cafile=self.ca_bundle)
        return ssl.create_default_context()


def substitute_marker(value: str, marker: str) -> str:
    """Replace the marker template used in active test manifests."""
    return value.replace("{{marker}}", marker)


def _links_finished(links: list[Mapping[str, Any]]) -> bool:
    if not links:
        return False
    terminal_statuses = {0, 1, -1, -2}
    statuses: list[int] = []
    for link in links:
        try:
            statuses.append(int(link.get("status", -3)))
        except (TypeError, ValueError):
            return False
    return all(status in terminal_statuses for status in statuses)
