"""Verified Windows EVTX field mappings.

These mappings are documented with sources and verification evidence.
Every mapping has been verified against:
- Wazuh Windows EventChannel decoder output
- Windows Event Log documentation
- Actual decoded Wazuh JSON fixtures
"""

from __future__ import annotations

from wazuh_sigma.fields.models import (
    ConfidenceLevel,
    FieldMapping,
    FieldNamespace,
    VerificationSource,
)

WINDOWS_FIELD_MAPPINGS = (
    # System fields - from Event/System element
    FieldMapping(
        sigma_field="EventID",
        wazuh_field="win.system.eventID",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Numeric event ID from Event/System/EventID",
    ),
    FieldMapping(
        sigma_field="event_id",
        wazuh_field="win.system.eventID",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.REPOSITORY_LEGACY,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Alias for EventID",
    ),
    FieldMapping(
        sigma_field="Provider_Name",
        wazuh_field="win.system.providerName",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Event provider name from Event/System/Provider@Name",
    ),
    FieldMapping(
        sigma_field="Channel",
        wazuh_field="win.system.channel",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Event log channel name from Event/System/Channel",
    ),
    FieldMapping(
        sigma_field="ComputerName",
        wazuh_field="win.system.computer",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Computer name from Event/System/Computer",
    ),
    FieldMapping(
        sigma_field="Hostname",
        wazuh_field="win.system.computer",
        namespace=FieldNamespace.SYSTEM,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/win32/wes/eventmanifestschema-systempropertiestype-element",
        verification_source=VerificationSource.REPOSITORY_LEGACY,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Alias for ComputerName",
    ),
    # EventData fields - common across multiple event types
    FieldMapping(
        sigma_field="Image",
        wazuh_field="win.eventdata.image",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Process image path from Sysmon Event 1, 3, etc. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="CommandLine",
        wazuh_field="win.eventdata.commandLine",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Process command line from Sysmon Event 1. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ParentImage",
        wazuh_field="win.eventdata.parentImage",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Parent process image from Sysmon Event 1. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ParentCommandLine",
        wazuh_field="win.eventdata.parentCommandLine",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Parent process command line from Sysmon Event 1. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SourceImage",
        wazuh_field="win.eventdata.sourceImage",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("create_remote_thread", "process_access"),
        documentation_reference="https://learn.microsoft.com/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.HIGH,
        notes="Source process image from Sysmon Event 8 (CreateRemoteThread) and Event 10 (ProcessAccess). Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="TargetImage",
        wazuh_field="win.eventdata.targetImage",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("create_remote_thread", "process_access"),
        documentation_reference="https://learn.microsoft.com/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.HIGH,
        notes="Target process image from Sysmon Event 8 (CreateRemoteThread) and Event 10 (ProcessAccess). Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ProcessId",
        wazuh_field="win.eventdata.processId",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Process ID from Sysmon. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ParentProcessId",
        wazuh_field="win.eventdata.parentProcessId",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Parent process ID from Sysmon. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="User",
        wazuh_field="win.eventdata.user",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="User name from Sysmon Event 1. Note: not always present; use with LogonGuid for auth events.",
    ),
    FieldMapping(
        sigma_field="TargetFilename",
        wazuh_field="win.eventdata.targetFilename",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="File path from Sysmon Event 11, 23, 26. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SourceIp",
        wazuh_field="win.eventdata.sourceIp",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Source IP from Sysmon Event 3 (Network Connection). Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="DestinationIp",
        wazuh_field="win.eventdata.destinationIp",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Destination IP from Sysmon Event 3. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SourcePort",
        wazuh_field="win.eventdata.sourcePort",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Source port from Sysmon Event 3. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="DestinationPort",
        wazuh_field="win.eventdata.destinationPort",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Destination port from Sysmon Event 3. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Protocol",
        wazuh_field="win.eventdata.protocol",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Network protocol from Sysmon Event 3. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Registry",
        wazuh_field="win.eventdata.registryPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Registry path from Sysmon Event 12, 13, 14. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="RegistryPath",
        wazuh_field="win.eventdata.registryPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Alias for Registry. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Details",
        wazuh_field="win.eventdata.details",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Registry value data from Sysmon Event 13. Exact camelCase required.",
    ),
    # Hash fields
    FieldMapping(
        sigma_field="Hashes",
        wazuh_field="win.eventdata.hashes",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Multi-hash string from Sysmon Event 1. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="MD5",
        wazuh_field="win.eventdata.md5",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="MD5 hash from Sysmon. Extracted from Hashes field. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SHA1",
        wazuh_field="win.eventdata.sha1",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="SHA1 hash from Sysmon. Extracted from Hashes field. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SHA256",
        wazuh_field="win.eventdata.sha256",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="SHA256 hash from Sysmon. Extracted from Hashes field. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Imphash",
        wazuh_field="win.eventdata.imphash",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Import hash from Sysmon Event 1. Exact camelCase required.",
    ),
    # Security event fields
    FieldMapping(
        sigma_field="LogonType",
        wazuh_field="win.eventdata.logonType",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        categories=("authentication",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Logon type from Security Event 4624. Values: 0=System, 2=Interactive, 3=Network, 4=Batch, 5=Service, 7=Unlock, 8=NetworkCleartext, 9=NewCredentials, 10=RemoteInteractive, 11=CachedInteractive, 12=CachedRemoteInteractive, 13=CachedUnlocked. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="LogonGuid",
        wazuh_field="win.eventdata.logonGuid",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        categories=("authentication",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Logon GUID from Security Event 4624. Unique identifier for the logon session. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="TargetUserName",
        wazuh_field="win.eventdata.targetUserName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Target user name (account being logged in to) from Security events. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SubjectUserName",
        wazuh_field="win.eventdata.subjectUserName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4627",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Subject user name (account performing the action) from Security events. Exact camelCase required.",
    ),
    # Network and system fields
    FieldMapping(
        sigma_field="TargetHostname",
        wazuh_field="win.eventdata.targetHostname",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5156",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.HIGH,
        notes="Target hostname from firewall/network events. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Domain",
        wazuh_field="win.eventdata.domain",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Domain name from Security events. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="DomainName",
        wazuh_field="win.eventdata.domainName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.HIGH,
        notes="Alias for Domain. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Account",
        wazuh_field="win.eventdata.accountName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4704",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.HIGH,
        notes="Account name from Security events. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ServiceName",
        wazuh_field="win.eventdata.serviceName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4697",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.HIGH,
        notes="Service name from Security Event 4697 and others. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="CallerProcessName",
        wazuh_field="win.eventdata.callerProcessName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5156",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Calling process name from firewall events. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    # DNS fields
    FieldMapping(
        sigma_field="QueryName",
        wazuh_field="win.eventdata.queryName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("dns-client",),
        documentation_reference="https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn800669(v=ws.11)",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="DNS query name from Microsoft-Windows-DNS-Client Event 3008. Exact camelCase required.",
    ),
    # Additional eventdata fields for comprehensive coverage
    FieldMapping(
        sigma_field="ProcessPath",
        wazuh_field="win.eventdata.processPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.HIGH,
        notes="Process image path (alternative field name). Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ExceptionCode",
        wazuh_field="win.eventdata.exceptionCode",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Exception code from Sysmon Event 5 (Process Terminated). Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="AuthenticationPackageName",
        wazuh_field="win.eventdata.authenticationPackageName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Authentication package name from Security Event 4624. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="IpAddress",
        wazuh_field="win.eventdata.ipAddress",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="IP address from Security Event 4624 and others. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="IpPort",
        wazuh_field="win.eventdata.ipPort",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="IP port from Security Event 4624. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="WorkstationName",
        wazuh_field="win.eventdata.workstationName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Workstation name from Security Event 4624. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="LogonProcessName",
        wazuh_field="win.eventdata.logonProcessName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Logon process name from Security Event 4624. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="SubjectUserSid",
        wazuh_field="win.eventdata.subjectUserSid",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Subject user SID from Security events. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="TargetUserSid",
        wazuh_field="win.eventdata.targetUserSid",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Target user SID from Security events. Verified in expanded fixture corpus (Phase 5 audit).",
    ),
    FieldMapping(
        sigma_field="Initiated",
        wazuh_field="win.eventdata.initiated",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("network_connection",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.WINDOWS_DOCUMENTATION,
        confidence=ConfidenceLevel.HIGH,
        notes="Sysmon Event 3 (Network Connection) Initiated field indicating if connection was initiated by local system. Values: 'true' or 'false'.",
    ),
    # Newly verified fields from real Wazuh log analysis (Phase 5 Production Audit)
    FieldMapping(
        sigma_field="CreationUtcTime",
        wazuh_field="win.eventdata.creationUtcTime",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 11 (File Create) - File creation time. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="EventType",
        wazuh_field="win.eventdata.eventType",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 13 (Registry Set Value) - Event type (CreateKey, SetValue, DeleteKey, etc.). Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="QueryResults",
        wazuh_field="win.eventdata.queryResults",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("dns_query",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 22 (DNS Query) - Query results. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="QueryStatus",
        wazuh_field="win.eventdata.queryStatus",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("dns_query",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 22 (DNS Query) - Query status code. Exact camelCase required.",
    ),
    # Restored fixture-backed Sysmon mappings. These fields were observed in
    # captured decoded fixtures under tests/fixtures/wazuh/windows/sysmon and
    # are intentionally scoped to the Sysmon categories that expose them.
    FieldMapping(
        sigma_field="OriginalFileName",
        wazuh_field="win.eventdata.originalFileName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create originalFileName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="OriginalFileName",
        wazuh_field="win.eventdata.originalFileName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load originalFileName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Description",
        wazuh_field="win.eventdata.description",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create description. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Description",
        wazuh_field="win.eventdata.description",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load description. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Product",
        wazuh_field="win.eventdata.product",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create product. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Product",
        wazuh_field="win.eventdata.product",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load product. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Company",
        wazuh_field="win.eventdata.company",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create company. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Company",
        wazuh_field="win.eventdata.company",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load company. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="IntegrityLevel",
        wazuh_field="win.eventdata.integrityLevel",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create integrityLevel. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ProcessGuid",
        wazuh_field="win.eventdata.processGuid",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon processGuid observed across captured Sysmon fixtures. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ParentProcessGuid",
        wazuh_field="win.eventdata.parentProcessGuid",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create parentProcessGuid. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ImageLoaded",
        wazuh_field="win.eventdata.imageLoaded",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load imageLoaded. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Signed",
        wazuh_field="win.eventdata.signed",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load signed. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Signature",
        wazuh_field="win.eventdata.signature",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load signature. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SignatureStatus",
        wazuh_field="win.eventdata.signatureStatus",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load signatureStatus. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="GrantedAccess",
        wazuh_field="win.eventdata.grantedAccess",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_access",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_10.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 10 Process Access grantedAccess. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="CallTrace",
        wazuh_field="win.eventdata.callTrace",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_access",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_10.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 10 Process Access callTrace. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="SourceProcessGuid",
        wazuh_field="win.eventdata.sourceProcessGUID",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_access",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_10.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 10 Process Access sourceProcessGUID. Exact Wazuh fixture casing required.",
    ),
    FieldMapping(
        sigma_field="TargetProcessGuid",
        wazuh_field="win.eventdata.targetProcessGUID",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_access",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_10.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 10 Process Access targetProcessGUID. Exact Wazuh fixture casing required.",
    ),
    FieldMapping(
        sigma_field="PipeName",
        wazuh_field="win.eventdata.pipeName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("pipe_created",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/operational_event_17.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 17 Pipe Created pipeName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="CurrentDirectory",
        wazuh_field="win.eventdata.currentDirectory",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create currentDirectory. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="FileVersion",
        wazuh_field="win.eventdata.fileVersion",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create fileVersion. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="FileVersion",
        wazuh_field="win.eventdata.fileVersion",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("image_load",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_7.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 7 Image Load fileVersion. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ParentUser",
        wazuh_field="win.eventdata.parentUser",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create parentUser. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="LogonId",
        wazuh_field="win.eventdata.logonId",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("process_creation",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/sysmon_event_1.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 1 Process Create logonId. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Contents",
        wazuh_field="win.eventdata.contents",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("create_stream_hash",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/operational_event_15.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 15 FileCreateStreamHash contents. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Hash",
        wazuh_field="win.eventdata.hash",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        categories=("create_stream_hash",),
        documentation_reference="tests/fixtures/wazuh/windows/sysmon/operational_event_15.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 15 FileCreateStreamHash hash. Exact camelCase required.",
    ),
    # Fixture-backed PowerShell, Security, System, and BITS mappings. Ambiguous
    # field names are scoped by service/category and are not global fallbacks.
    FieldMapping(
        sigma_field="ScriptBlockText",
        wazuh_field="win.eventdata.scriptBlockText",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("powershell",),
        categories=("ps_script",),
        documentation_reference="tests/fixtures/wazuh/windows/powershell/operational_event_4104.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="PowerShell Operational Event 4104 scriptBlockText. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Path",
        wazuh_field="win.eventdata.path",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("powershell",),
        categories=("ps_script",),
        documentation_reference="tests/fixtures/wazuh/windows/powershell/operational_event_4104.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="PowerShell Operational Event 4104 path. Scoped to ps_script because Path is ambiguous.",
    ),
    FieldMapping(
        sigma_field="Data",
        wazuh_field="win.eventdata.data",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("application",),
        documentation_reference="tests/fixtures/wazuh/windows/edgeupdate/application_event_0.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Application channel event data field. Scoped to Application service because Data is ambiguous.",
    ),
    FieldMapping(
        sigma_field="AppName",
        wazuh_field="win.eventdata.source",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("application",),
        documentation_reference="tests/fixtures/wazuh/windows/application/application_error_1000.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Application Error Event 1000 faulting application name decoded as source. Scoped to Application service.",
    ),
    FieldMapping(
        sigma_field="ExceptionCode",
        wazuh_field="win.eventdata.exceptionCode",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("application",),
        documentation_reference="tests/fixtures/wazuh/windows/application/application_error_1000.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Application Error Event 1000 exceptionCode. Scoped to Application service.",
    ),
    FieldMapping(
        sigma_field="Data",
        wazuh_field="win.eventdata.data",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("powershell-classic",),
        documentation_reference="tests/fixtures/wazuh/windows/powershell/windows_powershell_event_400.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows PowerShell Classic Event 400/403/600 data. Scoped to powershell-classic service.",
    ),
    FieldMapping(
        sigma_field="Data",
        wazuh_field="win.eventdata.data",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        categories=("ps_classic_start",),
        documentation_reference="tests/fixtures/wazuh/windows/powershell/windows_powershell_event_400.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows PowerShell Classic start event data. Scoped to ps_classic_start.",
    ),
    FieldMapping(
        sigma_field="Data",
        wazuh_field="win.eventdata.data",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        categories=("ps_classic_provider_start",),
        documentation_reference="tests/fixtures/wazuh/windows/powershell/windows_powershell_event_600.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows PowerShell Classic provider-start data. Scoped to ps_classic_provider_start.",
    ),
    FieldMapping(
        sigma_field="ImagePath",
        wazuh_field="win.eventdata.imagePath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("system",),
        documentation_reference="tests/fixtures/wazuh/windows/system/system_event_7045.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Service Control Manager Event 7045 imagePath. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ServiceFileName",
        wazuh_field="win.eventdata.imagePath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("system",),
        documentation_reference="tests/fixtures/wazuh/windows/system/system_event_7045.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sigma alias for Service Control Manager Event 7045 imagePath. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ServiceName",
        wazuh_field="win.eventdata.serviceName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("system",),
        documentation_reference="tests/fixtures/wazuh/windows/system/system_event_7045.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Service Control Manager Event 7045 serviceName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ObjectName",
        wazuh_field="win.eventdata.objectName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4662.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4662 objectName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="ProcessName",
        wazuh_field="win.eventdata.processName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4673.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security events processName observed in 4624/4648/4673/4674 fixtures. Scoped to Security service.",
    ),
    FieldMapping(
        sigma_field="ObjectType",
        wazuh_field="win.eventdata.objectType",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4662.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4662 objectType. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="AccessMask",
        wazuh_field="win.eventdata.accessMask",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4662.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4662/4674 accessMask. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="AccessList",
        wazuh_field="win.eventdata.accessList",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4662.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4662 accessList. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="PrivilegeList",
        wazuh_field="win.eventdata.privilegeList",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4672.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4672/4673/4674 privilegeList. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Service",
        wazuh_field="win.eventdata.service",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4673.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4673 service field. Scoped to Security service because Service is ambiguous.",
    ),
    FieldMapping(
        sigma_field="TargetName",
        wazuh_field="win.eventdata.targetName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_5379.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 5379 targetName. Scoped to Security service because TargetName is ambiguous.",
    ),
    FieldMapping(
        sigma_field="KeyLength",
        wazuh_field="win.eventdata.keyLength",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4624.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4624 keyLength. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Status",
        wazuh_field="win.eventdata.status",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4769.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security 4769/4776 status. Scoped to Security service because Status is ambiguous.",
    ),
    FieldMapping(
        sigma_field="Workstation",
        wazuh_field="win.eventdata.workstation",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("security",),
        documentation_reference="tests/fixtures/wazuh/windows/security/security_event_4776.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Security Event 4776 workstation field. Scoped to Security service because Workstation is ambiguous.",
    ),
    FieldMapping(
        sigma_field="ProcessPath",
        wazuh_field="win.eventdata.processPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("bits-client",),
        documentation_reference="tests/fixtures/wazuh/windows/bits_client/operational_event_3.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="BITS Client Operational Event 3 processPath. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="processPath",
        wazuh_field="win.eventdata.processPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("bits-client",),
        documentation_reference="tests/fixtures/wazuh/windows/bits_client/operational_event_3.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Lowercase Sigma field spelling used by BITS Client rules; maps to exact Wazuh processPath.",
    ),
    FieldMapping(
        sigma_field="LocalName",
        wazuh_field="win.eventdata.localName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("bits-client",),
        documentation_reference="tests/fixtures/wazuh/windows/bits_client/operational_event_16403.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="BITS Client Operational Event 16403 localName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="RemoteName",
        wazuh_field="win.eventdata.remoteName",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("bits-client",),
        documentation_reference="tests/fixtures/wazuh/windows/bits_client/operational_event_16403.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="BITS Client Operational Event 16403 remoteName. Exact camelCase required.",
    ),
    FieldMapping(
        sigma_field="Path",
        wazuh_field="win.eventdata.path",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("windefend",),
        documentation_reference="tests/fixtures/wazuh/windows/defender/operational_event_1116.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows Defender Operational Event 1116/1117 path. Scoped to windefend because Path is ambiguous.",
    ),
    FieldMapping(
        sigma_field="Path",
        wazuh_field="win.eventdata.path",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("taskscheduler",),
        documentation_reference="tests/fixtures/wazuh/windows/taskscheduler/operational_event_129.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="TaskScheduler Operational Event 129 path. Scoped to taskscheduler because Path is ambiguous.",
    ),
    FieldMapping(
        sigma_field="Action",
        wazuh_field="win.eventdata.action",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("firewall-as",),
        documentation_reference="tests/fixtures/wazuh/windows/security/firewall_event_2099.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows Firewall Event 2099 action field. Scoped to firewall-as service.",
    ),
    FieldMapping(
        sigma_field="ApplicationPath",
        wazuh_field="win.eventdata.applicationPath",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("firewall-as",),
        documentation_reference="tests/fixtures/wazuh/windows/security/firewall_event_2099.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows Firewall Event 2099 applicationPath field. Scoped to firewall-as service.",
    ),
    FieldMapping(
        sigma_field="ModifyingApplication",
        wazuh_field="win.eventdata.modifyingApplication",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("firewall-as",),
        documentation_reference="tests/fixtures/wazuh/windows/security/firewall_event_2006.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows Firewall Event 2006/2099 modifyingApplication field. Scoped to firewall-as service.",
    ),
    FieldMapping(
        sigma_field="NewValue",
        wazuh_field="win.eventdata.new Value",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("windefend",),
        documentation_reference="tests/fixtures/wazuh/windows/defender/operational_event_5007.json",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Windows Defender Event 5007 new Value field. Exact decoded Wazuh casing includes a space.",
    ),
    FieldMapping(
        sigma_field="TargetObject",
        wazuh_field="win.eventdata.targetObject",
        namespace=FieldNamespace.EVENTDATA,
        products=("windows",),
        services=("sysmon",),
        documentation_reference="https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon",
        verification_source=VerificationSource.DECODED_FIXTURE,
        confidence=ConfidenceLevel.VERIFIED,
        notes="Sysmon Event 13 (Registry Set Value) - Target registry path. Exact camelCase required.",
    ),
)
